###################################
## Section: Basic Configuration ##
###################################

# ----------------------
# Property: stream_name
# ----------------------
# Description: The name of the stream you want to scrape
# Example value: user_activities
#
stream_name: user_activities

# -------------------
# Property: shardIds
# -------------------
# Description: An array of shard ids to scrape. If a blank array is passed or the property is commented out,
# all shards will be scraped
#
# Example value for all shards:  (or just comment out the property entirely)
# shardIds: []
#
# Example value for a list of only specific shards to scrape:
# shardIds:
#  - shardId-000000000000
#  - shardId-000000000001
#
shardIds: []

# ---------------------------
# Property: starting_position
# ---------------------------
# Description: At which point in the stream should the scraper begin reading from?
# Possible values: AT_SEQUENCE_NUMBER|AFTER_SEQUENCE_NUMBER|TRIM_HORIZON|LATEST|AT_TIMESTAMP
#
# Note: TRIM_HORIZON = Start with the oldest record in the stream
#
starting_position: TRIM_HORIZON

# ---------------------------
# Property: timestamp
# ---------------------------
# Description: Only used if starting_position = AT_TIMESTAMP, otherwise just comment out the line
# Format (UTC): YYYY-MM-DD HH:MM:SS
#
timestamp: "2022-12-01 00:00:00"

# ---------------------------
# Property: sequence_number
# ---------------------------
# Description: Only used if starting_position = AT_SEQUENCE_NUMBER or AFTER_SEQUENCE_NUMBER
# otherwise just comment out the line
#
sequence_number: 49634793967732681113891714384157638505909056619063279650

#####################################
## Stream Processing Configuration ##
#####################################

# -------------------------------
# Property: max_records_per_shard
# -------------------------------
# Description: The maximum amount of records to retrieve per shard. If unlimited, comment out or set to 0
#
# Note: In some cases the amount of records fetched per shard may exceed the amount specified below,
# but only upto the poll_batch_size+max_records_per_shard due to record fetches always being called
# in batches as specified by the poll_batch_size
#
max_records_per_shard: 0

# -------------------------
# Property: poll_batch_size
# -------------------------
# Description: The number of records fetched per poll (used via boto3.kinesis.get_records(Limit=X))
#
# 
#
poll_batch_size: 100


# -------------------------------
# Property: max_empty_record_sets
# -------------------------------
# Description: The name of the stream you want to scrape
# Example value: user_activities
#
max_empty_record_polls: 100
