#
###################################
## Section: Basic Configuration ##
###################################

# ----------------------
# Property: stream_name
# ----------------------
# Description: The name of the stream you want to scrape
# Example value: user_activities
#
stream_name: user_activities

# -------------------
# Property: shardIds
# -------------------
# Description: An array of shard ids to scrape. If a blank array is passed or the property is commented out,
# all shards will be scraped
#
# Example value for all shards:  (or just comment out the property entirely)
# shardIds: []
#
# Example value for a list of only specific shards to scrape:
# shardIds:
#  - shardId-000000000000
#  - shardId-000000000001
#
shardIds: []

# ---------------------------
# Property: starting_position
# ---------------------------
# Description: At which point in the stream should the scraper begin reading from?
# Possible values: AT_SEQUENCE_NUMBER|AFTER_SEQUENCE_NUMBER|TRIM_HORIZON|LATEST|AT_TIMESTAMP
# Note: TRIM_HORIZON = Start with the oldest record in the stream
#
starting_position: TRIM_HORIZON

# ---------------------------
# Property: timestamp
# ---------------------------
# Description: Only used if starting_position = AT_TIMESTAMP
# Format (UTC): YYYY-MM-DD HH:MM:SS
#
timestamp: "2022-12-01 00:00:00"

#sequence_number: 1234 # Only use if position is either AT_SEQUENCE_NUMBER or AFTER_SEQUENCE_NUMBER


#
# Section: Processing Configuration
#
